### ISSUE TITLE
Multiple `Pillow` versions in `requirements.txt`

### ISSUE THREAD

**Issue by TheFloatingString** [ECC-BFMC/Computer#1]
Hi!

I noticed that `requirements.txt` has three different versions of the `Pillow` dependency, which interfered with the `pip install -r requirements.txt` command.

By chance, is it possible that only the most recent version of `Pillow` is required to run the code?

Thanks!

**Comment by BFMC-Rares-Lemnariu** [comment]
fixed here https://github.com/ECC-BFMC/Computer/commit/06201538b608cb81cace34b7c84966c3f10d98ca
